let products = [
    {
        "id": 1001,
        "title": "Math",
        "location": "Malta",
        "price": 20,
        "image": "images/math.jpg",
        "availableInventory": 5,
        "rating": 2,
    },
    {
        "id": 1002,
        "title": "English",
        "location": "London",
        "price": 50,
        "image": "images/english.png",
        "availableInventory": 5,
        "rating": 4,
    },
    {
        "id": 1003,
        "title": "History",
        "location": "Middlesex",
        "price": 30,
        "image": "images/history.jpg",
        "availableInventory": 5,
        "rating": 5,
    },
    {
        "id": 1004,
        "title": "Information Technology",
        "location": "Malta",
        "price": 40,
        "image": "images/it.jpg",
        "availableInventory": 5,
        "rating": 5,
    },
    {
        "id": 1005,
        "title": "Environmental Studies",
        "location": "Middlesex",
        "price": 60,
        "image": "images/env.png",
        "availableInventory": 5,
        "rating": 4,
    },
    {
        "id": 1006,
        "title": "Arts and Crafts",
        "location": "Dubai",
        "price": 15,
        "image": "images/a&c.jpg",
        "availableInventory": 5,
        "rating": 2,
    },
    {
        "id": 1007,
        "title": "Theatre Studies",
        "location": "Middlesex",
        "price": 25,
        "image": "images/theatre.png",
        "availableInventory": 5,
        "rating": 5,
    },
    {
        "id": 1008,
        "title": "Video Editing",
        "location": "Middlesex",
        "price": 35,
        "image": "images/video.png",
        "availableInventory": 5,
        "rating": 5,
    },
    {
        "id": 1009,
        "title": "Web Development",
        "location": "Middlesex",
        "price": 31,
        "image": "images/web.png",
        "availableInventory": 5,
        "rating": 5,
    },
    {
        "id": 1010,
        "title": "Mobile App Devlopment",
        "location": "Middlesex",
        "price": 43,
        "image": "images/mobile.png",
        "availableInventory": 5,
        "rating": 5,
    },

]